### ISSUE TITLE
适配一下2023.3呗

### ISSUE THREAD

**Issue by wdkGitHub** [godfather1103/p3c#23]
2023.3 不兼容

如果在 gradle配置文件中删除  `untilBuild.set("${yearVersion}${noVersion}.*")`   会忽略最大版本号

**Comment by godfather1103** [comment]
2023.3有些类跟方法被修改了，导致编译不通过，周末有时间再看看

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/edit/versions/stable/450678

等官方审核了

**Comment by godfather1103** [comment]
也可以去
https://github.com/godfather1103/p3c/releases/tag/2023.3
中下载离线包

**Comment by wdkGitHub** [comment]
👍

**Comment by godfather1103** [comment]
官方审核通过了
