### ISSUE TITLE
能否使专有名词在lowerCamel判定中合法

### ISSUE THREAD

**Issue by ShiinaKin** [godfather1103/p3c#27]
#4 这个commit似乎只能解决suffix为专有词的情况，并不是修改了lowerCamelCase的判定
如图，上面的方法名有修改建议：方法名【detailDTO2VO】不符合lowerCamelCase命名风格，下面则没有
![image](https://github.com/godfather1103/p3c/assets/52254895/ab660ce9-f94c-49af-bf19-6a3ec6c2e79f)

能否针对通用的lowerCamel判定规则增加自定义名词呢

**Comment by godfather1103** [comment]
https://github.com/godfather1103/p3c/blob/master/p3c-pmd/src/main/java/com/alibaba/p3c/pmd/lang/java/rule/naming/LowerCamelCaseVariableNamingRule.java
从官方原来定义的来看的确是匹配的后缀，从正常思考角度来看，专有名称不一定只会在结尾，我考虑一下后面怎么调整

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/edit/versions/beta/456443
试一下这个版本看看呢？没问题的话，我这边发正式版

**Comment by godfather1103** [comment]
@mashirot https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/edit/versions/beta/456443

**Comment by ShiinaKin** [comment]
看起来没问题
建议在readme里说明一下这个fork repository的enhancement
包括这个专有名词的用法是`LowerCamelCaseVariableNamingRule_WHITE_LIST=["VO", "AO", "BO", "DTO"]`这个属性
