### ISSUE TITLE
POJO类中的任何布尔类型的变量都不要加is 检查失败

### ISSUE THREAD

**Issue by zhujiaxin** [godfather1103/p3c#29]
## 规约原文
POJO类中的任何布尔类型的变量，都不要加is，否则部分框架解析会引起序列化错误
## 问题描述
当类中有属性为布尔类型的时候，无法正常检测。使用包装类的规约检查出来了，但是is开头的没有检查出来
## 修改建议
不知道是为什么
idea的版本为2023.1.3   
插件版本为1.4-2023.1-2.1.1-ext
![image](https://github.com/godfather1103/p3c/assets/30893925/8e1b9190-507f-48c4-858a-1040ae60c533)

**Comment by godfather1103** [comment]
2023.3推送了对应的修复，等待官方审核，其他版本的IDEA看看周末有没有时间推送了

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/versions/stable/468061
