### ISSUE TITLE
变量名驼峰提示错行

### ISSUE THREAD

**Issue by changingshow** [godfather1103/p3c#39]
## 规约原文
变量名【Cell】不符合lowerCamelCase命名风格 

## 问题描述
idea版本：IntelliJ IDEA 2023.3.3 (Ultimate Edition)
插件版本：1.6-2023.3-2.1.1-ext-6

提示变量名驼峰规则错行，如图所示
![GIF 2024-3-25 14-12-21](https://github.com/godfather1103/p3c/assets/7709440/3cc0e2c4-9c16-4fb2-b0d0-ce9b3b842882)

根据提示是说【Cell】不符合命名规则，但是提示阴影却在一个方法名上面，根据提示点击之后，没有任何变量名变化。

尝试过重启idea，重新打开文件，重启电脑，重新安装插件，都无法解决这个问题，怀疑是太多代码中文注释导致的错行？

## 修改建议

请尝试修复此问题。

**Comment by godfather1103** [comment]
这个应该是idea本身卡了造成的，我这边也不好处理
