### ISSUE TITLE
无法本地导入插件到新版idea中

### ISSUE THREAD

**Issue by a1243412811** [godfather1103/p3c#40]
[Alibaba_Java_Coding_Guidelines_Fix_Some_Bug_-1.6-2023.2-2.1.1-ext-6-signed.zip](https://github.com/godfather1103/p3c/files/14786786/Alibaba_Java_Coding_Guidelines_Fix_Some_Bug_-1.6-2023.2-2.1.1-ext-6-signed.zip)
![image](https://github.com/godfather1103/p3c/assets/53896723/3a9f4a24-8f1e-478a-b454-1a889831495b)

**Comment by a1243412811** [comment]
在线下载是没问题的 但是我在内网环境下没有网络 使用zip包导入就会报错。

**Comment by godfather1103** [comment]
![1](https://github.com/godfather1103/p3c/assets/11797964/f542e938-2ec9-4edb-bedd-cbe1ca9c518e)

**Comment by godfather1103** [comment]
你要看清楚版本啊，你下载2023.2的去2023.3上面肯定有问题啊
