### ISSUE TITLE
idea2023.3.6社区版扫描不出来

### ISSUE THREAD

**Issue by wsczm** [godfather1103/p3c#42]
![Uploading image.png…]()

**Comment by godfather1103** [comment]
图片没有上传成功

**Comment by wsczm** [comment]
![image](https://github.com/godfather1103/p3c/assets/37656284/dd043b36-79f4-4271-9378-7b55b59d5bc4)
右键扫描 右下角弹出如下提示

**Comment by godfather1103** [comment]
这段代码感觉没啥问题吧

**Comment by godfather1103** [comment]
<img width="947" alt="iShot_2024-04-07_18 19 40" src="https://github.com/godfather1103/p3c/assets/11797964/7c50c22c-0c61-4392-b8ef-00faf30d6e07">

我这边是最新版的2024.1，是可以扫描的，你这边确认2023.6扫描有问题？

**Comment by godfather1103** [comment]
<img width="1027" alt="iShot_2024-04-07_18 22 56" src="https://github.com/godfather1103/p3c/assets/11797964/482d861a-43a3-4773-b3ed-44662d886c8e">
