### ISSUE TITLE
如何手动执行jar或mvn命令来手动检测代码并输出报告？

### ISSUE THREAD

**Issue by krismileji** [godfather1103/p3c#47]
背景：
在idea中编写代码使用检测没有问题，但不能保证所有人都安装一样的idea版本和插件版本，从源头上很难规避。

期望：
在提交代码或编译时进行手动检测，并输出检测报告。

ps：我记得原版好像是有这个功能的，以前还用过，可以输出text或html格式的，时间有点久了。

**Comment by godfather1103** [comment]
这个是基于pmd实现的，添加pmd插件，增加对应规则就行了
https://pmd.github.io/
https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html
https://docs.gradle.org/current/userguide/pmd_plugin.html#sec:pmd_configuration

规则依赖
```xml
<dependency>
    <groupId>io.github.godfather1103.p3c</groupId>
    <artifactId>p3c-pmd</artifactId>
    <version>2.1.1-ext-6</version>
</dependency>
```

**Comment by krismileji** [comment]
已经验证过可以了，感谢，这个仓库中的rulesets中的规则是和插件检测的一致吗

**Comment by godfather1103** [comment]
插件中用的是其子集，没有应用全部规则

**Comment by godfather1103** [comment]
https://github.com/godfather1103/p3c/blob/master/idea-plugin/p3c-common/src/main/resources/rulesets/java/ali-pmd.xml

**Comment by krismileji** [comment]
明白了

**Comment by krismileji** [comment]
还有个小问题想请教下，对于标记了@Nullable的字段，有办法扫描出来吗，还是已经存在这个规则了，另外可以更新下群的二维码吗

**Comment by godfather1103** [comment]
二维码更新了

**Comment by ghfengg** [comment]
群二维码又过期了
