### ISSUE TITLE
包装类规约问题

### ISSUE THREAD

**Issue by CShisan** [godfather1103/p3c#56]
## 规约原文
'isTrue(java.lang.Boolean, com.xxx.exception.Code, java.lang.String)' in 'com.xxx.exception.Asserter' cannot be applied to '(boolean, com.quick.common.exception.Code, java.lang.String)'
## 问题描述
方法签名`isTrue(java.lang.Boolean, com.xxx.exception.Code, java.lang.String)`
![image](https://github.com/user-attachments/assets/3cbfbeba-5b04-4881-a712-a467748b9028)

## 修改建议
不报错

**Comment by godfather1103** [comment]
<img width="1628" alt="iShot_2024-08-20_16 17 22" src="https://github.com/user-attachments/assets/877c935c-6289-4d8c-850f-ee426c0d85ba">

不太清楚你这个报错是哪儿来的，我本地没有复现

**Comment by CShisan** [comment]
> <img alt="iShot_2024-08-20_16 17 22" width="1628" src="https://private-user-images.githubusercontent.com/11797964/359396609-877c935c-6289-4d8c-850f-ee426c0d85ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDI1MjcsIm5iZiI6MTcyNDE0MjIyNywicGF0aCI6Ii8xMTc5Nzk2NC8zNTkzOTY2MDktODc3YzkzNWMtNjI4OS00ZDhjLTg1MGYtZWU0MjZjMGQ4NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNmE2MjBmOTVlMjVmMGE1YTQ3MmNkMmMzNTJmMzk2ZmFjOTJlMGRlYjY5Y2YzYWM1MTEwOTZlNGY3YzdhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pTK3jqMq1jjjxNqMxeP5PR023sPH7cyKDf-8AvHrSyk">
> 不太清楚你这个报错是哪儿来的，我本地没有复现

额,,,,现在我也复现不了     昨天更新了IDEA和插件就一直报这个错     重启IDEA和清缓存都不行    今天不知道为啥又不报错了

**Comment by godfather1103** [comment]
从截图来看，对应的错误提醒应该是idea本身自带的，跟插件的检查无关

**Comment by CShisan** [comment]
> 从截图来看，对应的错误提醒应该是idea本身自带的，跟插件的检查无关

好的    谢谢解答
