### ISSUE TITLE
对于引用record类型的类，都会无法扫描

### ISSUE THREAD

**Issue by itqzy** [godfather1103/p3c#6]
是对记录类型未适配吗？
![image](https://github.com/godfather1103/p3c/assets/45928094/0af784d5-28f7-423e-ba69-75178c04bb9f)

**Comment by godfather1103** [comment]
p3c-pmd里面的PMD版本是6.15.0，支持的Java版本应该只到了12-13左右，record类应该不支持

**Comment by godfather1103** [comment]
预计晚上推送一个测试版

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/versions/beta
可以先试用一下beta版，没问题的话，周末就推正式版
@itqzy

**Comment by godfather1103** [comment]
已经提交了1.4正式版，等待IDEA审核
