### ISSUE TITLE
namelist.properties 是干嘛用的

### ISSUE THREAD

**Issue by YuchuZhang** [godfather1103/p3c#8]
如题 不知道这个怎么用

**Comment by godfather1103** [comment]
https://github.com/godfather1103/p3c/issues/4#issuecomment-1686085660

**Comment by godfather1103** [comment]
阿里官方在这个里面增加了一个配置项用于自定义需要忽略的专有名词，例如，你们需要把DATA结尾的类也认为是POJO，就可以通过自定义配置上去配置，把对应的类纳入POJO的PMD检测分析中

**Comment by YuchuZhang** [comment]
ok 感谢了

> 阿里官方在这个里面增加了一个配置项用于自定义需要忽略的专有名词，例如，你们需要把DATA结尾的类也认为是POJO，就可以通过自定义配置上去配置，把对应的类纳入POJO的PMD检测分析中
