### ISSUE TITLE
Java17使用遇问题的到

### ISSUE THREAD

**Issue by klinge1011** [godfather1103/p3c#9]
## 问题描述
1.record类型无法识别，class类内部record被识别为方法
![image](https://github.com/godfather1103/p3c/assets/34301334/b1391f07-cdc1-481b-ad97-268300207af9)

2.新的switch语法不支持
![image](https://github.com/godfather1103/p3c/assets/34301334/0827c3a5-a59c-40be-84da-26a187df5ff0)

## 修改建议
支持一下Java17O(∩_∩)O

**Comment by godfather1103** [comment]
预计晚上推个测试版，增加了一些对Record类的检验规则，以及Switch的default块的校验

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-/versions/beta
可以先试用一下beta版，没问题的话，周末就推正式版
@klinge1011

**Comment by godfather1103** [comment]
已经提交了1.4正式版，等待IDEA审核

**Comment by klinge1011** [comment]
牛哇
